### ISSUE TITLE
Ribbon icons are too large

### ISSUE THREAD

**Issue by liamrwilkins** [ThioJoe/EditClipboardContents#2]
Running from Windows 11, the Icons in the header appear too large. 
My display is 1920x1080p, at 100% scale, but changing either the resolution or scale in the Windows settings has no effect on the in-app icon scaling.

Icons clip in both windowed, and full screen modes.

![image](https://github.com/user-attachments/assets/f4f22a0c-1348-4e84-b8b5-97cdfb0aebf1)
![image](https://github.com/user-attachments/assets/f09415c2-d130-42b8-abb9-1352f09749af)

**Comment by ThioJoe** [comment]
Ok this should be fixed with the latest release version 1.5.1
