### ISSUE TITLE
Icon button to big

### ISSUE THREAD

**Issue by mniesen** [ThioJoe/EditClipboardContents#3]
Version: 1.5.0
Windows 10 22H2 (build 19045.5073)
Monitor: 1680x1050

The icon buttons are for some reason to big.
![afbeelding](https://github.com/user-attachments/assets/d75b666c-c532-405c-b672-755fc921e9b8)

After setting the ImageScalingSize property of toolStrip1 to 25; 25 the buttons are the correct size.
![afbeelding](https://github.com/user-attachments/assets/a1072a13-975f-4d3a-8d73-5b0ce0ab1546)

![afbeelding](https://github.com/user-attachments/assets/8d95af18-ac24-4390-a21a-075aeac42a45)

**Comment by ThioJoe** [comment]
Ok i think i fixed it with the latest commit but i'll want to test a bit more before doing a release. 

There's some other issues i noticed with controls positioning i want to be sure to iron out

**Comment by mniesen** [comment]
Can confirm, the icon size is fixed.
![afbeelding](https://github.com/user-attachments/assets/44fd3ef6-20c1-404a-bff2-88aefef0c10f)
